import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { createServer } from '../frontend/node_modules/vite/dist/node/index.js';
import React from '../frontend/node_modules/react/index.js';
import { renderToStaticMarkup as render } from '../frontend/node_modules/react-dom/server.node.js';
const server=await createServer({root:fileURLToPath(new URL('../frontend',import.meta.url)),configFile:false,esbuild:{jsx:'automatic'},server:{middlewareMode:true,ws:false},appType:'custom',optimizeDeps:{noDiscovery:true}});
try {
 const {default:View}=await server.ssrLoadModule('/src/components/CommunityView.tsx');
 const {default:Activity}=await server.ssrLoadModule('/src/components/WorkshopActivity.tsx');
 const {default:Navigation}=await server.ssrLoadModule('/src/components/PresentationSwitcher.tsx');
 const {emptyWorkshopResponses,impressionOptions,toggleImpression,discussionPrompt}=await server.ssrLoadModule('/src/workshop.ts');
 const {STARTER_LABEL,STARTER_SOURCE,workshopExampleLabel}=await server.ssrLoadModule('/src/workshopExamples.ts');
 const noop=()=>{};
 const props={active:true,trainer:false,report:null,providers:null,examples:[{name:'podcast.m4a'},{name:'presentation.pptx'}],name:'',url:null,hasInput:false,busy:false,running:false,status:'',caption:'',mode:'general',onCaption:noop,onMode:noop,onFile:noop,onExample:noop,onAnalyse:noop,onNewSession:noop,onStepChange:noop,onSecondOpinionTarget:noop};
 const html=render(React.createElement(View,props));
 assert.match(html, /<option value="illustration-1.png" selected="">Community table scene \(practice example\)<\/option>/);
 assert.match(html, /Try the four workshop steps with this practice example/);
 assert.match(html, /<option value="podcast.m4a">Podcast<\/option>/);
 assert.match(html, /<option value="presentation.pptx">Presentation slides<\/option>/);
 assert.doesNotMatch(html,/AI-generated illustration|AI-generated workshop illustration|created with AI using|Choose an example/);
 const uploaded=render(React.createElement(View,{...props,hasInput:true,name:'my-file.png',url:'blob:local'}));
 assert.match(uploaded,/Current file: my-file.png/);
 assert.match(uploaded,/<option value="" selected="">/);
 const selected=render(React.createElement(View,{...props,hasInput:true,name:'presentation.pptx',thumbnail:'/preview.png'}));
 assert.match(selected,/<option value="presentation.pptx" selected="">Presentation slides/);
 const activity={kind:'image',report:null,busy:false,responses:emptyWorkshopResponses(),onChange:noop,onNext:noop,onPrevious:noop,onReviewChecks:noop,onEndSession:noop,onNewSession:noop,onViewEvidence:noop,sessionStatus:'',sourceNote:STARTER_SOURCE};
 for(const step of ['notice','discuss','reflect']) assert(!render(React.createElement(Activity,{...activity,step})).includes(STARTER_SOURCE));
 assert(render(React.createElement(Activity,{...activity,step:'check'})).includes(STARTER_SOURCE));
 assert.doesNotMatch(render(React.createElement(Activity,{...activity,step:'check'})),/source record has yet/);
 const choices=impressionOptions('image');
 assert.equal(choices.length,5); assert(!choices.includes('Human-made'));
 assert.deepEqual(toggleImpression(['Photo'],'Not sure yet'),['Not sure yet']);
 assert.deepEqual(toggleImpression(['Not sure yet'],'Mix of human and AI'),['Mix of human and AI']);
 assert.match(discussionPrompt(['Photo']),/photographed/);
 assert.match(discussionPrompt(['Drawn or painted by a person']),/drawing or illustration/);
 assert.equal(workshopExampleLabel('OpenAI-secret-name.png',10),'Example 11');
 const nav=render(React.createElement(Navigation,{value:'community',onChange:noop}));
 assert(nav.indexOf('value="community"')<nav.indexOf('value="facilitator"'));
 assert(nav.indexOf('value="facilitator"')<nav.indexOf('value="developer"'));
 console.log('Notice review: neutral practice caption/alt, selected dropdown, friendly labels, provenance reveal, choices and navigation passed.');
} finally {await server.close();}
