// Static "showcase" mode: when built with VITE_SHOWCASE=1 the app serves cached
// real analyses from /showcase/*.json instead of calling a backend. No keys, no
// uploads, no live LLM calls. The normal build is completely unaffected.
import packageInfo from "../package.json";
import type { ExampleEntry, GraphData, Report } from "./types";
import type { DiffusionSummary } from "./api";

export const SHOWCASE = import.meta.env.VITE_SHOWCASE === "1";
export const CONFERENCE = !SHOWCASE && import.meta.env.VITE_CONFERENCE === "1";
export const EXAMPLES_ONLY = SHOWCASE || CONFERENCE;
export const WORKSHOP_STARTER_NAME = "illustration-1.png";
// Workshop variant: hide the interactive second-opinion panel entirely (its
// buttons open external vendor pages), for facilitator-led sessions where the
// live step is shown as slides instead. Cached second-opinion NOTES on records
// still display: they are part of the stored analysis, not an interaction.
export const HIDE_SECOND_OPINION = import.meta.env.VITE_HIDE_SECOND_OPINION === "1";
const BASE = import.meta.env.BASE_URL || "/";

export interface ShowcaseExample {
  id: string;
  name: string;
  kind: string;
  report: string;
  preview: string | null;
  thumb: string | null;
  verdict: string;
  rating: number | null;
}
interface Manifest {
  baked_at: string;
  models: string[];
  examples: ShowcaseExample[];
  workshop_starter?: ShowcaseExample;
}

let _manifest: Promise<Manifest> | null = null;
export function manifest(): Promise<Manifest> {
  if (!_manifest) _manifest = fetch(`${BASE}showcase/manifest.json`, { cache: "no-store" }).then((r) => r.json());
  return _manifest;
}

// Original example files are copied into the bundle by build_showcase.sh so
// visitors can download them (e.g. to attach in their own second-opinion
// checks) - all of them, podcast included (unlocked 2026-07-13: the Zenodo
// record is for methodological citation, not a gate on usability).
export async function showcaseExamples(): Promise<ExampleEntry[]> {
  return (await manifest()).examples.map((e) => ({
    name: e.name,
    downloadUrl: `${BASE}showcase/originals/${encodeURIComponent(e.name)}`,
  }));
}

async function entryFor(name: string): Promise<ShowcaseExample> {
  const m = await manifest();
  const e = m.workshop_starter?.name === name ? m.workshop_starter : m.examples.find((x) => x.name === name);
  if (!e) throw new Error("That example is not in the showcase set.");
  return e;
}

// Images, audio and video load the selected bundled original; documents use a thumbnail.
export async function showcasePreview(name: string): Promise<{ url: string | null; kind: string }> {
  const e = await entryFor(name);
  if (e.kind === "audio" || e.kind === "video") return { url: `${BASE}showcase/originals/${encodeURIComponent(e.name)}`, kind: e.kind };
  return { url: e.preview ? `${BASE}showcase/${e.preview}` : null, kind: e.kind };
}

// The baked first page/slide (or cover art / waveform) for the documents and
// audio that have no bundled preview image. bake_showcase.py already writes
// this into the manifest for every record, so no extra fetch is needed.
export async function showcaseThumb(name: string): Promise<string | null> {
  return (await entryFor(name)).thumb;
}

export async function showcaseReport(name: string): Promise<Report> {
  const e = await entryFor(name);
  const response = await fetch(`${BASE}showcase/${e.report}`);
  if (!response.ok) throw new Error("Recorded findings could not be opened. Please try again.");
  return response.json();
}

// Pre-baked export files (generated at bake time by the same server-side
// builders the full tool uses, so showcase downloads match the full tool).
export async function showcaseExportUrl(name: string, fmt: "md" | "csv" | "pptx" | "pdf"): Promise<string> {
  const e = await entryFor(name);
  return `${BASE}showcase/exports/${e.id}.${fmt}`;
}

// Pre-baked per-item verdict maps (graph + deterministic summary + exports),
// generated by bake_showcase.py with the same server code the full tool runs.
export async function showcaseVerdictMap(name: string): Promise<GraphData> {
  const e = await entryFor(name);
  return fetch(`${BASE}showcase/reports/${e.id}_vmap.json`).then((r) => r.json());
}
export async function showcaseVerdictMapSummary(name: string): Promise<DiffusionSummary> {
  const e = await entryFor(name);
  return fetch(`${BASE}showcase/reports/${e.id}_vmap_summary.json`).then((r) => r.json());
}
export async function showcaseVmapFileUrl(
  name: string, which: "gexf" | "csv" | "png", mode = "verdict", light = false,
): Promise<string> {
  const e = await entryFor(name);
  if (which === "gexf") return `${BASE}showcase/exports/${e.id}_vmap.gexf`;
  // PNGs are pre-baked once per colour mode AND theme so the download matches
  // the screen (light chrome for the light/console themes).
  if (which === "png") return `${BASE}showcase/exports/${e.id}_vmap-by-${mode}${light ? "-light" : ""}.png`;
  return `${BASE}showcase/exports/${e.id}_vmap-csv.zip`;
}

export function showcaseGraph(): Promise<GraphData> {
  return fetch(`${BASE}showcase/graph.json`).then((r) => r.json());
}
export function showcaseSummary(): Promise<DiffusionSummary> {
  return fetch(`${BASE}showcase/graph_summary.json`).then((r) => r.json());
}
export function showcaseFileUrl(which: "gexf" | "csv" | "png", mode = "verdict", light = false): string {
  if (which === "gexf") return `${BASE}showcase/sda-showcase.gexf`;
  if (which === "png") return `${BASE}showcase/sda-showcase-by-${mode}${light ? "-light" : ""}.png`;
  return `${BASE}showcase/sda-showcase-csv.zip`;
}

// A static providers object so the header chips render without a backend.
export function showcaseProviders() {
  const ready = { configured: true, state: "recorded", model: "cached" };
  const na = { configured: false, state: "unconfigured", model: "" };
  return {
    tool: "SDA Vision", version: packageInfo.version, vaccine_lens: false, dev_mode: false,
    corpus_available: false,
    claude: ready, openai: ready, gemini: ready, synthid: na,
    c2pa: { configured: true, state: "recorded", model: "" },
    local: { configured: true, state: "recorded", model: "" },
  };
}

export async function showcaseBakedAt(): Promise<{ date: string; models: string[] }> {
  const m = await manifest();
  return { date: m.baked_at, models: m.models };
}
